// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module6.Tp1.DataAccessLayer;

namespace Module6.Tp1.DataAccessLayer.Migrations
{
    [DbContext(typeof(DojoContext))]
    [Migration("20220525074814_AjoutArtsMartiaux")]
    partial class AjoutArtsMartiaux
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtsMartiauxId")
                        .HasColumnType("int");

                    b.Property<int>("SamouraisId")
                        .HasColumnType("int");

                    b.HasKey("ArtsMartiauxId", "SamouraisId");

                    b.HasIndex("SamouraisId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("Module6.Tp1.DataAccessLayer.Entities.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SamouraiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SamouraiId")
                        .IsUnique()
                        .HasFilter("[SamouraiId] IS NOT NULL");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("Module6.Tp1.DataAccessLayer.Entities.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartiaux");
                });

            modelBuilder.Entity("Module6.Tp1.DataAccessLayer.Entities.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Samourais");
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("Module6.Tp1.DataAccessLayer.Entities.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("ArtsMartiauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Module6.Tp1.DataAccessLayer.Entities.Samourai", null)
                        .WithMany()
                        .HasForeignKey("SamouraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Module6.Tp1.DataAccessLayer.Entities.Arme", b =>
                {
                    b.HasOne("Module6.Tp1.DataAccessLayer.Entities.Samourai", "Samourai")
                        .WithOne("Arme")
                        .HasForeignKey("Module6.Tp1.DataAccessLayer.Entities.Arme", "SamouraiId");

                    b.Navigation("Samourai");
                });

            modelBuilder.Entity("Module6.Tp1.DataAccessLayer.Entities.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
